git submodule add --depth 1 https://github.com/tpope/vim-pathogen.git
git submodule add --depth 1 https://github.com/scrooloose/nerdtree.git
git submodule add --depth 1 https://github.com/Xuyuanp/nerdtree-git-plugin.git
git submodule add --depth 1 https://github.com/jistr/vim-nerdtree-tabs.git
git submodule add --depth 1 https://github.com/altercation/vim-colors-solarized.git
git submodule add --depth 1 https://github.com/HerringtonDarkholme/yats.vim.git
git submodule add --depth 1 https://github.com/Valloric/YouCompleteMe.git
git submodule add --depth 1 https://github.com/vim-syntastic/syntastic.git
git submodule add --depth 1 https://github.com/raimondi/delimitmate
git submodule add --depth 1 https://github.com/vim-scripts/matchit.zip
git submodule add --depth 1 https://github.com/Valloric/ListToggle.git
